# Время наблюдения за сектором. В секундах
observation-time = 30    
# Желаемое разрешение видео
target-width = 1280
target-height = 720
vehicle-classes = ["bus", "car", "motobike", "road_train", "truck"]
# Коэффиценты привидения
vehicle-size-coeffs = { "car" = 1, "motorbike" = 0.5, "truck" = 1.8, "road_train" = 2.7, "bus" = 2.2 }
